#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include "PrepareData.h"
#include <wx/wx.h>
#include <wx/dcbuffer.h>

#define PANEL_WIDTH 500 
#define PANEL_HEIGHT 500
//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_button1_click( wxCommandEvent& event );
		void m_button2_click( wxCommandEvent& event );
		void m_button3_click( wxCommandEvent& event );
		void m_button4_click( wxCommandEvent& event );
		void m_cb_color_click( wxCommandEvent& event );
		void m_s_rotation_onscroll( wxScrollEvent& event );
		void m_s_tilt_onscroll( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		wxBitmap m_bitmap;
		wxImage m_image;
		bool ShowColor = false;
		int choice = 0;
		float tilt = 100;
		double alpha = 133;
		void Draw(int N, float d[100][3], bool ShowColor, double alpha);
		void Repaint();








};

extern float FunctionData[100][3];
extern int NoPoints;

#endif // __GUIMyFrame1__
